### ISSUE TITLE
如何解读 profile？

### ISSUE THREAD

**Issue by zensh** [ali-sdk/node-profiler#11]
记得 5月12日 @JacksonTian 朴神为我等 [Teambition](https://www.teambition.com) 的小伙伴们现场开光，得道后我当晚即对 [thunks](https://github.com/thunks/thunks) 进行了一番优化，执行效率立马涨了一截。记得当时的主要优化点是用类 new 对象取代了直接创建对象。

这两天回头研究 node-profiler，想做进一步优化，对 thunks 优化前后的版本分别进行了切片研究，发现并没有看懂（老啦，忘啦）~

主要问题有：
1. `of Hidden Classes Created` 表明了什么意义？
2. 部分绿色（象征优化成功）代码行存在 `Reason for Deoptimization`，为何？

**优化前：**
![qq20150720-1 2x](https://cloud.githubusercontent.com/assets/863754/8823410/113fb1ce-309f-11e5-9620-84473f4a09d0.png)
![qq20150720-2 2x](https://cloud.githubusercontent.com/assets/863754/8823412/1145dafe-309f-11e5-8489-4356365d6665.png)

**优化后：**
![qq20150720-3 2x](https://cloud.githubusercontent.com/assets/863754/8823413/11478444-309f-11e5-92eb-be6a9578771e.png)
![qq20150720-4 2x](https://cloud.githubusercontent.com/assets/863754/8823411/1144ae54-309f-11e5-97e4-d857c04bb380.png)

**Comment by jkeylu** [comment]
期待能够写些关于通过 node-profiler 进行优化的案例或文章
