### ISSUE TITLE
跑一个express出现的问题

### ISSUE THREAD

**Issue by Shidou** [ali-sdk/node-profiler#13]
webkit-devtools-agent: Spawning websocket service process...
start agent

webkit-devtools-agent: A proxy got connected.
webkit-devtools-agent: Waiting for commands...
webkit-devtools-agent: Websockets service started on 0.0.0.0:9999

webkit-devtools-agent: new frontend connection!

Page.canScreencast is not implemented
Network.enable is not implemented
Page.getResourceTree is not implemented
Runtime.enable is not implemented
DOM.enable is not implemented
CSS.enable is not implemented
Timeline.enable is not implemented
Database.enable is not implemented
DOMStorage.enable is not implemented
Profiler.setSamplingInterval is not implemented
Worker.setAutoconnectToWorkers is not implemented
Runtime.isRunRequired is not implemented
HeapProfiler.enable is not implemented
Page.setShowViewportSizeOnResize is not implemented
Worker.setAutoconnectToWorkers is not implemented
Worker.setAutoconnectToWorkers is not implemented

**Comment by JacksonTian** [comment]
这个不是问题，抛出的警告。

**Comment by Shidou** [comment]
有没有文档对测试数据的说明的
