### ISSUE TITLE
好像不支持ES6语法

### ISSUE THREAD

**Issue by CoderIvan** [ali-sdk/node-profiler#15]
RT

**Comment by JacksonTian** [comment]
当前只兼容到了node v0.12.6。

**Comment by hetz** [comment]
@JacksonTian 求兼容新的 node 版本。

**Comment by violet-day** [comment]
+1

**Comment by JacksonTian** [comment]
推荐使用 alinode来做调优操作。

**Comment by nickeljew** [comment]
alinode 是不是 node-profiler的商用版？后者是不是不再跟进开发了？

**Comment by JacksonTian** [comment]
alinode和node-profiler功能上有部分重叠。前者用于生产环境，后者只能用于线下调试，但结果更丰富。

以目前的开发资源，应该是没法将这些功能port到新的版本上了。

**Comment by nickeljew** [comment]
不如开源吧

**Comment by CoderIvan** [comment]
我觉得上面的问题已经离题了

如果这个ISSUE算是已经解答了的话，就关闭这个ISSUE吧
