### ISSUE TITLE
如何找出异步等待的时间长的代码块

### ISSUE THREAD

**Issue by liaolunhui** [ali-sdk/node-profiler#18]
我的一个Node接口很慢，用这个node-profiler也没分析出原因。
后来才发现，我的程序经常要到：http://ip.taobao.com/service/getIpInfo.php?ip=127.0.0.1查询IP归属，同一个IP查询超过2次后，此接口就会将连接挂起，等30秒才响应。

可能profiler记录CPU运行的时间，可是很多都是异步操作，请求发出去后，CPU又去干其他事情去了。
很害怕哪天我的另外一个接口又很慢了，如何找出这种耗时的异步操作？

**Comment by JacksonTian** [comment]
异步I/O调用并不能反映在CPU的热点函数上的。推荐你用我们的alinode，其中的慢HTTP可以找出你应用中响应慢的接口和响应慢的依赖。 http://alinode.aliyun.com/
