### ISSUE TITLE
CPU监控显示不正确

### ISSUE THREAD

**Issue by FoghostCn** [ali-sdk/node-profiler#19]
![qq20160422-0 2x](https://cloud.githubusercontent.com/assets/5020327/14730798/5c7fe310-087c-11e6-92cb-9c93a28d81f0.png)

如图所示，实际上我这台机器是4核的，top显示实际的cpu占用只有50%而已，但是这里的监控显示的CPU是200%，我想是不是你们的CPU占用只是拿到百分比后简单的相加了而已而没有除以核心数。

还有就是我的agentx进程时不时的会死掉，不知道是什么原因。

**Comment by yjhjstz** [comment]
请提供下alinode 的版本，agentx 的版本？

另外 agentx 是否有日志输出？

**Comment by FoghostCn** [comment]
`agentx -v : 1.5.0`
`which node :  ~/.tnvm/versions/alinode/v1.5.1/bin/node`

agentx 的日志中基本都是：

```
2016-04-22 10:50:42.632 Error: Error: ENOENT: no such file or directory, stat '/alidata/log/socket-error.log '
    at Error (native)
```

也就是我在agentx的启动配置中设置的error_log地址：

```
"error_log": [
    "/alidata/log/socket-error.log ",
    "/alidata/log/http-error.log"
  ]
```

**Comment by yjhjstz** [comment]
- cpu 是我们显示不一致
- agentx 是用 nohup 启动的？有些 shell 会有问题，需启动后手动exit 退出ssh.

**Comment by FoghostCn** [comment]
是nohup启动的，用的你们阿里云的机器。
CentOS release 6.5 (Final) 系统自带的shell

**Comment by JacksonTian** [comment]
其实是对的。node-cpu这个数据，不是整体的数据，而是单个CPU的占比。所以你4core的机器的话，就是200% / 4 ~= 50%。确实是没有除以核心数。

**Comment by JacksonTian** [comment]
nohup的问题跟你ssh上去的shell貌似有点关系。可用主动 exit 下。
