### ISSUE TITLE
linux表示被歧视了...

### ISSUE THREAD

**Issue by huyinghuan** [ali-sdk/node-profiler#3]

**Comment by JacksonTian** [comment]
你是什么版本。目前打包好了deb包。rpm包待打包。

**Comment by huyinghuan** [comment]
@JacksonTian  我用的是deb， 那就是官方网站的下载链接没有放出来

**Comment by JacksonTian** [comment]
下午发布。

**Comment by JacksonTian** [comment]
已经更新： http://alinode.aliyun.com/releases http://alinode.aliyun.com/releases

**Comment by huyinghuan** [comment]
看到了 已下载
