### ISSUE TITLE
Log无法正常显示信息~

### ISSUE THREAD

**Issue by biebg** [ali-sdk/node-profiler#4]
Mac 10.10.4  
不能正常显示log  
![浏览器debug](http://7fvazv.com1.z0.glb.clouddn.com/node_profilerQQ20150713-1@2x.png)
![terminal](http://7fvazv.com1.z0.glb.clouddn.com/node_profilerQQ20150713-2@2x.png)

**Comment by JacksonTian** [comment]
这个log是正常的。无视掉。 XXXXX is not implemented 都是正常。warning的意思。不是真正的错误。

**Comment by biebg** [comment]
好的，谢谢~ 是我的打开方式不对  :)
