### ISSUE TITLE
主从多进程模型无法使用

### ISSUE THREAD

**Issue by zhangziqiu** [ali-sdk/node-profiler#6]
我这里自己开发的类似cluster的模型,其实也是按照深入浅出nodejs中介绍的开发的, 主进程负责监听socket端口, 并且负责把socket传递给子进程. 请问如何这种模型中使用node-profiler啊? 我这里不是http, 直接使用的socket类, 客户端使用的是protobuf协议长连接进行通讯.

**Comment by JacksonTian** [comment]
调试性能只要开单个进程就可以了。不管是通过什么协议，能保持代码长期运行以及在采样时给足压力即可。

**Comment by zhangziqiu** [comment]
多谢Jackson, 我改了改程序让工作进程可以单独启动, 已经成功使用了node-profiler.  
非常期待node-profiler开源, 很想好好学习一下是如何实现的!

**Comment by JacksonTian** [comment]
thanks.
